### PR TITLE
Update db name in logData.py

### PR DESCRIPTION
**Pull request by johnpmitsch**
Looks like the couchdb name is mvp_data, this commit
updates to this name, which seems to fix the charts
showing incorrectly in the UI.

### CODE REVIEW

**Comment by webbhm** [comment]
This is a request against tag 2.1 on a file that is no longer a part of the builds.

**Comment by johnpmitsch** [comment]
@webbhm I'm a bit confused. This was an issue I had to fix on an install that I did last week, have things changed since then? Does the master branch not contain the latest code?

**Comment by johnpmitsch** [comment]
@webbhm 
I see this file in the latest 3.1.6 tarball:

```
[jomitsch@jomitsch tmp]$ cat mvp-3.1.6/MVP/web/cgi-bin/logData.py
from datetime import tzinfo, datetime
import requests
import json


#Output to file
def logData(name, status, attribute, value, comment):
    timestamp = '{:%Y-%m-%d %H:%M:%S}'.format(datetime.utcnow())
    logDB(timestamp, name, status, attribute, value, comment)
    
def logDB(timestamp, name, status, attribute, value, comment):
    log_record = {'timestamp' : timestamp,
            'name' : name,
            'status' : status,
            'attribute' : attribute,
            'value' : value,
            'comment' : comment}
    json_data = json.dumps(log_record)
    print(json.dumps(log_record, indent=4, sort_keys=True))
    headers = {'content-type': 'application/json'}
    r = requests.post('http://localhost:5984/mvp_sensor_data', data = json_data, headers=headers)
    print(r.json())

#Uncomment to test this function
#logData(_si7021, _Success, _temperature, '27', '')    
```

**Comment by webbhm** [comment]
"master" is the latest code, but it is often a work in progress, and not
guaranteed to be stable (though we try to keep it that way).  Tagged
releases are the 'official' packages of code that have been tested and we
believe are stable.  There have been no changes in the last week, but the
process takes more than downloading the files from github; that is why the
build script manages the download.
The build script code within the README file should always be pulling from
the latest stable release.  The last change was to make the database a
download of a binary file, instead of going through the whole database
compile (we encountered some bugs within the CouchDB build).  This created
a new path through various scripts (since the binary contained the database
with views that previously had to be added), as well as some permissions
changes.

**Comment by johnpmitsch** [comment]
@webbhm I'm still not clear on this. I think the file does exist in the latest build and the change needs to be made. Here is why:

- I used the build script from the readme to set up my system, which in your description pulls the latest release, and the graphs didn't display properly. I was able to resolve with this fix.
- The latest tagged release is 3.1.6 on github, and the build script in the README is hardcoded to pull the 3.1.6 release.
- If I unpack the 3.1.6 tarball taken from github, I see the file I have edited in this PR. I mention that in a [previous comment](https://github.com/futureag/mvp/pull/22#issuecomment-432666705)
- You say I am making a change in a file that is no longer a part of the builds, but it is in the master branch, which I assume is the lastest (and unstable) version of the code. Why would the file exist in the master branch and a 2.1 build, but not 3.1.6?
- Another user on the thread that stemmed this PR hit the same UI issue as myself (in addition to another db issue). He was using the build script as well.

I hope I've provided enough info to show why I think this file exists and the incorrect db name is affecting users. Apologies if I'm missing anything obvious.

**Comment by johnpmitsch** [comment]
@webbhm Ok I think I get what you are saying now.

Even though `logData.py` is *present* in the latest builds, its not actually being used. I guess there was an older way of submitting the data. I assumed that it was being used since it was in the build.

I "fixed" the UI issue becuase I switched to an incognito window, which cleared the browser cache, displaying the right charts. This just happened to coincide with the code change I did, so I got a false positive.

It might be a good idea to get rid of the dead code to avoid confusion. Sorry for the noise!

**Comment by webbhm** [comment]
Did you by chance build over an older version?  I am looking at github
(both master and 3.1.6) and not seeing the file.  I downloaded 3.1.6 and
did not see it there either.  If you built over an older version, it may
not have removed the old files when it downloaded the new.  Just a guess.
Either way, glad to see that you are running.

HW

**Comment by johnpmitsch** [comment]
@webbhm I appreciate your patience :) 

I used the build the script in the README gave me, which looks to be 3.1.6. The file I'm looking at is `MVP/web/cgi-bin/logData.py` which I see here in the master branch in Github: https://github.com/futureag/mvp/blob/master/MVP/web/cgi-bin/logData.py.

I wouldn't be able to make this Pull Request against  the master branch if the file didn't exist in master. Maybe try grepping for `mvp_sensor_data` in master or the extracted builds?

Things are working fine after resolving the caching issue. Thanks again for the help :+1:

**Pull request closed without merging**
